#!/bin/sh
#java -Xmx8G -cp `./classpath.sh bin` -Dlog4j.configuration=log4j.properties com.oltpbenchmark.DBWorkload $@
java -Xmx8G -Dlog4j.configuration=log4j.properties -jar target/oltpbench-1.0-jar-with-dependencies.jar "$@"
