#!/bin/sh
#java -Xmx8G -cp `./classpath.sh bin` -Dlog4j.configuration=log4j.properties com.oltpbenchmark.DBWorkload $@
java -Dfile.encoding="UTF-8" -Xmx8G -cp `./classpath.sh bin` -Dlog4j.configuration=log4j.properties -jar target/oltpbench-1.0-SNAPSHOT-jar-with-dependencies.jar "$@"
